IF OBJECT_ID('dbo.migrates', 'U') IS NULL
CREATE TABLE [migrates] (
  [id] BIGINT IDENTITY(1,1) PRIMARY KEY,
  [name] NVARCHAR(255) NOT NULL UNIQUE,
  [checksum] NVARCHAR(64),
  [created] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  [updated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
