BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "migrate_logs" (
    "id" NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "migrate_name" VARCHAR2(255) NOT NULL,
    "direction" VARCHAR2(8) NOT NULL,
    "status" VARCHAR2(16) NOT NULL,
    "finished_at" TIMESTAMP,
    "duration_ms" NUMBER(10),
    "error_message" CLOB,
    "created" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
