CREATE TABLE IF NOT EXISTS "migrates" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" VARCHAR(255) NOT NULL UNIQUE,
  "checksum" VARCHAR(64),
  "created" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
