[package]
name = "deterministic-migraters"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "migrate-setup"
path = "src/bin/migrate_setup.rs"

[[bin]]
name = "migrate-up"
path = "src/bin/migrate_up.rs"

[[bin]]
name = "migrate-down"
path = "src/bin/migrate_down.rs"

[[bin]]
name = "migrate-create"
path = "src/bin/migrate_create.rs"

[dependencies]
dotenvy = "0.15"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "sqlite", "postgres", "mysql"] }
time = "=0.3.47"
