CREATE TABLE IF NOT EXISTS "migrates" (
  "id" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL UNIQUE,
  "checksum" VARCHAR(64),
  "created" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
