CREATE TABLE IF NOT EXISTS `migrate_logs` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `migrate_name` VARCHAR(255) NOT NULL,
  `direction` VARCHAR(8) NOT NULL,
  `status` VARCHAR(16) NOT NULL,
  `finished_at` TIMESTAMP NULL,
  `duration_ms` INT,
  `error_message` TEXT,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
